config/routes.rb
Feedpad::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
 
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
 
  ActiveAdmin.routes(self)

  resources :channels do
    resources :articles do
      get 'star' => 'articles#star_article'
    end
  end

  get 'articles/starred' => 'articles#starred'

  match '*path' => redirect { |p, req| req.flash[:error] = "Oops! The page you requested was not found."; '/' }, via: :get # redirigir todas las rutas que no macheen al index

  root :to => 'channels#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :channel

  require 'feedzirra'

  def self.generate_articles(url, channel_id)
    feed = Feedzirra::Feed.fetch_and_parse(url)
    add_entries(feed.entries, channel_id)
    channel = Channel.find(channel_id)
    if !channel.name
      channel.name = feed.title
      channel.save
    end
  end

  def self.add_entries(entries, channel_id)
    entries.each do |entry|
      unless exists? :link => entry.url
        create!(
          :title => entry.title,
          :link => entry.url,
          :description => entry.summary,
          :pubDate => entry.published,
          :channel_id => channel_id,
          :unread => "yes",
          :star => "no"
        )
      end
    end
  end
  
  def self.update_feeds
    User.all.each do |u|
      u.channels.each do |c|
        Article.generate_articles(c.url, c.id)
      end
    end
  end

  def self.unread
    where(:unread => "yes")
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :articles
  belongs_to :user

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:google_oauth2]
  
  has_many :channels

  #validates :first_name, presence: true
  #validates_length_of :first_name, :maximum => 50, :message => "should be less than 50 characters"
  #validates :last_name, presence: true
  #validates_length_of :last_name, :maximum => 50, :message => "should be less than 50 characters"
  #validates :login_name, presence: true
  #validates_length_of :login_name, :maximum => 50, :message => "should be less than 50 characters"

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(login_name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20]
        )
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def star_article
		@article = Article.find(params[:article_id])
		@channel = Channel.find(params[:channel_id])
		if @article.star == "no"
			@article.update_attributes(star: "yes")
		else
			@article.update_attributes(star: "no")
		end
		respond_to do |format|
          format.js
        end
	end

	def starred
		@starred = current_user.channels.to_a.collect {|c| c.articles.to_a }.flatten.select { |x| x.star == "yes" }.sort_by { |x| x.created_at }.reverse!
	end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  before_filter :authenticate_user!

  def new
    @channel = current_user.channels.build
  end
  
  def index
    @channels = current_user.channels
    @latest_articles = current_user.channels.to_a.collect {|c| c.articles.to_a }.flatten.last(5)
  end
  
  def create
    @channel = Channel.new(channel_params)
    @channel.user_id = current_user.id

    respond_to do |format|
      if @channel.save
        format.html { redirect_to channels_path, notice: "Subscription to the channel was successful"}
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end

    Article.generate_articles(@channel.url, @channel.id)
  end

  def show
    @channel = Channel.find(params[:id])
    @articles = @channel.articles.order('pubDate DESC')
    @articles.each do |a|
      if a.unread
        a.update_attributes(:unread => "no")
      end
    end
  end
    
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy
 
    redirect_to channels_path
  end
  
  private
  def channel_params
    params.require(:channel).permit(:url)
  end

  def set_channel
    @channel = current_user.channels.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  before_filter :configure_permitted_parameters

protected
# permitir parametros custom
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :first_name, :last_name, :login_name, :password, :password_confirmation)
    end
   devise_parameter_sanitizer.for(:account_update) do |u|
     u.permit(:email, :first_name, :last_name, :login_name, :password, :password_confirmation, :current_password)
     end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
     
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_star.html.haml
- if article.star == "yes"
  = link_to raw("<i class='fa fa-star fa-lg'></i>"), channel_article_star_path(@channel.id, article.id), :remote => true
- else
  = link_to raw("<i class='fa fa-star-o fa-lg'></i>"), channel_article_star_path(@channel.id, article.id), :remote => true

app/views/articles/star_article.js.erb
$('#stars_<%= @article.id %>').html("<%= escape_javascript(render 'articles/star', :article => @article, :channel => @channel) %>")

app/views/articles/starred.html.erb
<p>
<h2>Showing favorite articles for <%= current_user.login_name %>: </h2>
<br />
 
<center>
<table id="articles" class="table table-striped table-condensed table-hover">
 <tbody>
  <% @starred.each do |starred| %>
    <tr>
      <td class="span4"><%= link_to(starred.title, starred.link) %></td>
      <td class="span5"><%= truncate(starred.description.gsub(/(<[^>]+>)/, '').gsub("&aacute;", "á").gsub("&eoacute;", "é").gsub("&iacute;", "í").gsub("&oacute;", "ó").gsub("&uacute;", "ú").gsub("&ntilde;", "ñ"), length: 60, separator: ' ') %></td> 
      <td class="span2"><%= time_ago_in_words(starred.pubDate, include_seconds: true) %> ago</td>
    </tr>
  <% end %>
</tbody>
</table>
</center>

<p>
</p>

app/views/channels/_new.html.haml
%p
  %h2 New Channel:
  = form_for :channel, url: channels_path do |f|
    %p
      = f.text_field :url, placeholder: "URL"
    %p
      = f.submit "Create Channel", :class => "btn btn-success"

app/views/channels/index.html.haml
%p
  %h2
    Showing newest articles for #{current_user.login_name}
  %br/
  %center
    %table#channels.table.table-striped.table-condensed.table-hover
      %thead
        %tr
          %th Name
          %th Description
          %th
          %th
      %tbody
        - @latest_articles.each do |article|
          %tr
            %td.span5= article.title
            %td.span7= article.description.gsub(/(<[^>]+>)/, '').gsub("&aacute;", "á").gsub("&eoacute;", "é").gsub("&iacute;", "í").gsub("&oacute;", "ó").gsub("&uacute;", "ú").gsub("&ntilde;", "ñ")

app/views/channels/new.html.erb
<p>
<h2>New Channel: </h2>

<%= form_for :channel, url: channels_path do |f| %>
  <p>
    <%= f.label :name, "Name: " %><%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :url, "URL: " %><%= f.text_field :url %>
  </p>
 
  <p>
    <%= f.submit "Create Channel", :class => "btn btn-success" %>
  </p>
<% end %>

app/views/channels/show.html.haml
%p
  %h2
    Showing articles for #{@channel.name}:
  %br/
  %center
    %table#articles.table.table-striped.table-condensed.table-hover
      %tbody
        - @articles.each do |article|
          %tr
            %td.span1
              %div{:id => "stars_#{article.id}"}
                = render 'articles/star', :article => @articles.find(article.id)
            %td.span4= link_to(article.title, article.link)
            %td.span5= truncate(article.description.gsub(/(<[^>]+>)/, '').gsub("&aacute;", "á").gsub("&eoacute;", "é").gsub("&iacute;", "í").gsub("&oacute;", "ó").gsub("&uacute;", "ú").gsub("&ntilde;", "ñ"), length: 60, separator: ' ')
            %td.span2
              = time_ago_in_words(article.pubDate, include_seconds: true)
              ago
  %center
    = link_to 'Unsuscribe from this channel', channel_path(@channel), class: "btn btn-primary", method: :delete, data: { confirm: 'Press OK to confirm channel deletion' }
  %p

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Feedpad", channels_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Feedpad
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    - if !current_user
      %main{:role => "main"}
        .container
          .content
            .row
              .span12
                = render 'layouts/messages'
                = yield
            %footer
    - else
      .box
        .row-fluid
          .column.span3
            %ul.nav.nav-list.nav-fixed-sidebar
              %a#go.btn.btn-warning{:href => "#newrss"}
                %i.icon-plus.icon-white
                Suscribe
              %li.divider
              %li.nav-header Navigation
              <li class=#{'active' if action_name == "index"}>#{link_to raw('<i class="fa fa-rss"></i> Home'), channels_path}
              - if action_name == "starred"
                %li.active
                  %a{:href => articles_starred_path}
                    %i.fa.fa-star
                    Starred
              - else
                %li
                  %a{:href => articles_starred_path}
                    %i.fa.fa-star
                    Starred
              %li.divider
              %li.nav-header My Channels
              - current_user.channels.each do |c|
                - if !c.name.blank?
                  <li class=#{'active' if params[:id] == "#{c.id}"}>
                  - if c.articles.unread.count > 0
                    = link_to "<b>#{c.name} <span class='badge unread-count'>#{c.articles.unread.count}</span></b>".html_safe, channel_path(c)
                  - else
                    = link_to c.name, channel_path(c)
          .column.span9
            = render 'layouts/messages'
            = yield
    #newrss
      = render 'channels/new'